name: Test

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    unit:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Install
              run: composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest

            - name: Unit tests
              run: ./vendor/bin/phpunit
